name: "Checkout shared Qt"
description: "Downloads a prebuilt shared Qt and outputs its absolute path"

inputs:
  version:
    required: true
    description: "Qt long version, e.g. 6.10.0"
  compiler:
    required: false
    description: "Compiler for Windows, e.g. llvm1706|msvc2022"
outputs:
  qtpath:
    description: "Path to qt"
    value: ${{ steps.windows.outputs.qtpath }}

runs:
  using: composite
  steps:
    - id: windows
      shell: powershell
      if: runner.os == 'Windows'
      run: |
        $os = $env:RUNNER_OS.ToLower()
        $arch = ($env:PROCESSOR_ARCHITECTURE.ToLower() -replace '^amd64$', 'x64')
        Start-BitsTransfer -Source `
          "https://github.com/k61n/qt_shared_builds/releases/download/${{inputs.version}}/qt${{inputs.version}}_shared_${os}_${{inputs.compiler}}_${arch}.zip" `
          -Destination .
        7z x .\qt${{inputs.version}}_shared_${os}_${{inputs.compiler}}_${arch}.zip `
          -o"./qt${{inputs.version}}"
        Remove-Item "qt${{inputs.version}}_shared_${os}_${{inputs.compiler}}_${arch}.zip"
        $path = (Resolve-Path "qt${{inputs.version}}").Path
        Add-Content -Path $env:GITHUB_OUTPUT -Value "qtpath=${path}"
