name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows-arm:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: windows-arm64
            comp: msvc2022
            flags: ""
          - os: windows-arm64
            comp: llvm1706
            flags: -no-sql-odbc -- -DCMAKE_C_COMPILER="clang.exe" -DCMAKE_CXX_COMPILER="clang++.exe" -G"Ninja"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-arm64
        id: build
        with:
          vvv:    "6.8.3"
          vv:     "6.8"
          comp:   ${{matrix.comp}}
          flags:  ${{matrix.flags}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build.outputs.fn}}
          path: ${{steps.build.outputs.path}}
